### ISSUE TITLE
error with primitives table

### ISSUE THREAD

**Issue by esizikova** [nileshkulkarni/volumetricPrimitivesPytorch#2]
Hi, Thanks for the code. I'm running into the following issue when running it:

```
(pytorch) nat-oitwireless-inside-vapornet100-c-14271:experiments lena$ python cadAutoEncCuboids/primSelTsdfChamfer.py --disp=False --nParts=20 --nullReward=0 --probLrDecay=0.0001 --shapeLrDecay=0.01 --synset=03001627 --numTrainIter=20000 --name=chairChamferSurf_null_small_init_prob0pt0001_shape0pt01
Iter	Err	TSDF	Chamf	MeanRe
 0.0000000	 0.0000000	 0.0000000	 0.0000000	 0.0000000
Traceback (most recent call last):
  File "cadAutoEncCuboids/primSelTsdfChamfer.py", line 241, in <module>
    loss, coverage, consistency, mean_reward = train(dataloader, netPred, reward_shaper, optimizer, iter)
  File "cadAutoEncCuboids/primSelTsdfChamfer.py", line 125, in train
    predParts, stocastic_actions = netPred.forward(inputVol) ## B x nPars*11
  File "cadAutoEncCuboids/primSelTsdfChamfer.py", line 199, in forward
    primitives, stocastic_actions = self.primitivesTable(features)
  File "/Users/lena/anaconda/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/lena/Documents/styleNet/volumetricPrimitivesPytorch/modules/primitives.py", line 166, in forward
    output, stocastic_outputs = l(feature)
  File "/Users/lena/anaconda/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/lena/Documents/styleNet/volumetricPrimitivesPytorch/modules/primitives.py", line 137, in forward
    quat = self.quatPred(feature)
  File "/Users/lena/anaconda/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/lena/Documents/styleNet/volumetricPrimitivesPytorch/modules/primitives.py", line 68, in forward
    x = normalize(x)
  File "/Users/lena/Documents/styleNet/volumetricPrimitivesPytorch/modules/primitives.py", line 73, in normalize
    x  = x/ (1E-12 + torch.norm(x, dim=1, p=2).expand(x.size()))
RuntimeError: The expanded size of the tensor (4) must match the existing size (32) at non-singleton dimension 1


```

**Comment by nileshkulkarni** [comment]
Just confirming this PyTorch version 0.1.12?

All that code is trying to do is make the predicted quaternion unit norm. You could try and replace it with your own function. Dimensions for x should ideally be N x 4. Could check if x is a 2D tensor?
